### ISSUE TITLE
How to work admin checker?

### ISSUE THREAD

**Issue by cr4shed666o** [Thomas-Smyth/SquadJS#236]
How does it work await this.server.getAdminsWithPermission? 
The canseeadminchat command was issued in admins, but despite this, it still does not define me as an administrator

**Comment by ect0s** [comment]
If your adminlist groups have spaces with the perms, this is possibly the issue. 

https://github.com/Team-Silver-Sphere/SquadJS/blob/cdf3a1e36d9c051c3041827019a17836f56bde24/squad-server/utils/admin-lists.js#L50

This should be a simple fix

**Comment by ect0s** [comment]
`groups[`${idx}-${m.groups.groupID}`] = m.groups.groupPerms.replace(/\s/g, "").split(','); `

Would be a fix.. but realistically I kind of hate that.

Might be able to get away with a .trim(), but a full regex would 100% work since OWI hasn't released any permissions with spaces (and likely won't, if I have an understanding of how they are doing things under the hood in UE4)
